# Generated by Django 4.2.7 on 2025-11-04 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformation_code', models.CharField(help_text='Código único auto-generado', max_length=50, unique=True, verbose_name='Código de Transformación')),
                ('weight_qq', models.DecimalField(decimal_places=2, help_text='Peso en quintales del café pergamino obtenido', max_digits=10, verbose_name='Peso Pergamino (qq)')),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en libras (calculado automáticamente)', max_digits=10, null=True, verbose_name='Peso (lbs)')),
                ('yield_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje de rendimiento cereza → pergamino (15-25% típico)', max_digits=5, verbose_name='Rendimiento (%)')),
                ('voucher_image', models.ImageField(help_text='Foto del vale de transformación', upload_to='transformations/vouchers/%Y/%m/%d/', verbose_name='Foto del Vale')),
                ('ocr_raw_text', models.TextField(blank=True, verbose_name='Texto OCR sin procesar')),
                ('ocr_weight_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Confianza OCR Peso (%)')),
                ('ocr_yield_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Confianza OCR Rendimiento (%)')),
                ('ocr_processed', models.BooleanField(default=False, verbose_name='OCR Procesado')),
                ('manual_correction', models.BooleanField(default=False, verbose_name='Corrección Manual')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En Proceso'), ('completed', 'Completado'), ('verified', 'Verificado')], default='pending', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('transformation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Transformación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(blank=True, help_text='Lote asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformations', to='lots.lot', verbose_name='Lote')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformations', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
            options={
                'verbose_name': 'Transformación',
                'verbose_name_plural': 'Transformaciones',
                'ordering': ['-transformation_date'],
            },
        ),
        migrations.CreateModel(
            name='TransformationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transformations/additional/%Y/%m/%d/', verbose_name='Imagen')),
                ('image_type', models.CharField(choices=[('voucher', 'Vale'), ('before', 'Antes (Cereza)'), ('after', 'Después (Pergamino)'), ('process', 'Proceso'), ('quality', 'Control de Calidad'), ('other', 'Otra')], default='other', max_length=20, verbose_name='Tipo de Imagen')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='transformation.transformation', verbose_name='Transformación')),
            ],
            options={
                'verbose_name': 'Imagen de Transformación',
                'verbose_name_plural': 'Imágenes de Transformación',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transformation',
            index=models.Index(fields=['-transformation_date'], name='transformat_transfo_cc58a3_idx'),
        ),
        migrations.AddIndex(
            model_name='transformation',
            index=models.Index(fields=['lot', '-transformation_date'], name='transformat_lot_id_157d58_idx'),
        ),
        migrations.AddIndex(
            model_name='transformation',
            index=models.Index(fields=['status'], name='transformat_status_56ecba_idx'),
        ),
    ]
