# Generated by Django 4.2.7 on 2025-09-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ocupado', 'Ocupado'), ('libre', 'Libre'), ('mantenimiento', 'Mantenimiento'), ('forzado', 'Forzado')], max_length=20, verbose_name='Estado')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Motivo')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('is_automatic', models.BooleanField(default=True, verbose_name='Automático')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='areas.area', verbose_name='Área')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='lots.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Ocupación',
                'verbose_name_plural': 'Ocupaciones',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['area', 'timestamp'], name='occupation__area_id_ef333d_idx'), models.Index(fields=['timestamp'], name='occupation__timesta_288538_idx')],
            },
        ),
    ]
