# Generated by Django 4.2.7 on 2025-10-20 14:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('dia', 'Día'), ('noche', 'Noche')], max_length=10, verbose_name='Turno')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('meal_type', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('refrigerio', 'Refrigerio')], max_length=20, verbose_name='Tipo de Comida')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('employee_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Empleados')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Total')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('pagado', 'Pagado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('approved_by', models.CharField(blank=True, max_length=200, verbose_name='Aprobado Por')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('payment_method', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], max_length=20, verbose_name='Método de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vale de Comida',
                'verbose_name_plural': 'Vales de Comida',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('herreria', 'Herrería'), ('electricidad', 'Electricidad')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('requested_by', models.CharField(max_length=200, verbose_name='Solicitado Por')),
                ('requested_date', models.DateField(verbose_name='Fecha de Solicitud')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('approved_by', models.CharField(blank=True, max_length=200, verbose_name='Aprobado Por')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Estimado')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Real')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Material',
                'verbose_name_plural': 'Solicitudes de Materiales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hora', 'Por Hora'), ('dia', 'Por Día')], max_length=10, verbose_name='Tipo de Pago')),
                ('worker_name', models.CharField(max_length=200, verbose_name='Nombre del Trabajador')),
                ('worker_id', models.CharField(blank=True, max_length=100, verbose_name='ID Trabajador')),
                ('work_description', models.TextField(verbose_name='Descripción del Trabajo')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas')),
                ('days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días')),
                ('rate_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa por Hora')),
                ('rate_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa por Día')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Total')),
                ('work_date', models.DateField(verbose_name='Fecha de Trabajo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('pagado', 'Pagado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('approved_by', models.CharField(blank=True, max_length=200, verbose_name='Aprobado Por')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('payment_method', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], max_length=20, verbose_name='Método de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vale de Pago',
                'verbose_name_plural': 'Vales de Pago',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad')),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Estimado')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Real')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='gestions.materialrequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='FoodTicketEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200, verbose_name='Nombre del Empleado')),
                ('employee_id', models.CharField(blank=True, max_length=100, verbose_name='ID Empleado')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='gestions.foodticket', verbose_name='Vale')),
            ],
            options={
                'verbose_name': 'Empleado en Vale',
                'verbose_name_plural': 'Empleados en Vale',
            },
        ),
    ]
