# Generated by Django 4.2.7 on 2025-10-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodticket',
            name='meal_type',
            field=models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena')], max_length=20, verbose_name='Tipo de Comida'),
        ),
    ]
