# Generated by Django 4.2.7 on 2025-09-17 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('record_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=10, verbose_name='Tipo')),
                ('origin', models.CharField(choices=[('fingerprint', 'Huella'), ('manual', 'Manual')], max_length=20, verbose_name='Origen')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Válido')),
                ('observations', models.CharField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='ID Dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-timestamp'],
            },
        ),
    ]
