# Generated by Django 4.2.7 on 2025-10-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['-timestamp'], name='attendance__timesta_2bf202_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', '-timestamp'], name='attendance__employe_e9bfd4_idx'),
        ),
    ]
