# Generated by Django 4.2.7 on 2025-10-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_attendance__timesta_2bf202_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'timestamp'], name='attendance__employe_d2a742_idx'),
        ),
    ]
