# Generated by Django 4.2.7 on 2025-09-17 02:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operador_seco', 'Operador Seco'), ('operador_humedo', 'Operador Húmedo'), ('catador', 'Catador'), ('rrhh', 'Recursos Humanos'), ('invitado', 'Invitado')], default='invitado', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temperature', 'Temperatura'), ('sensor_offline', 'Sensor Desconectado'), ('occupation', 'Ocupación'), ('fermentation', 'Fermentación'), ('attendance', 'Asistencia'), ('system', 'Sistema')], max_length=50)),
                ('rule', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('acknowledged', 'Reconocido'), ('resolved', 'Resuelto'), ('disabled', 'Deshabilitado')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('cooldown_minutes', models.IntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value_json', models.TextField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('general', 'General'), ('temperature', 'Temperatura'), ('fermentation', 'Fermentación'), ('cupping', 'Catación'), ('attendance', 'Asistencia'), ('alerts', 'Alertas')], default='general', max_length=50)),
                ('param_type', models.CharField(choices=[('string', 'Texto'), ('number', 'Número'), ('boolean', 'Booleano'), ('json', 'JSON')], default='string', max_length=20)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('user_login', 'Login de Usuario'), ('user_logout', 'Logout de Usuario'), ('sensor_reading', 'Lectura de Sensor'), ('occupation_change', 'Cambio de Ocupación'), ('lot_created', 'Lote Creado'), ('lot_updated', 'Lote Actualizado'), ('fermentation_started', 'Fermentación Iniciada'), ('fermentation_completed', 'Fermentación Completada'), ('cupping_created', 'Catación Creada'), ('attendance_marked', 'Asistencia Marcada'), ('alert_triggered', 'Alerta Disparada'), ('system_error', 'Error del Sistema')], max_length=50)),
                ('payload_json', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='info', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
