# Generated by Django 4.2.7 on 2025-09-27 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('usuarios', 'Usuarios'), ('empleados', 'Empleados'), ('proveedores', 'Proveedores'), ('catacion', 'Catación'), ('integracion_lotes', 'Integración de Lotes'), ('pesos_envio', 'Pesos Envío'), ('temperaturas', 'Temperaturas'), ('fermentacion', 'Fermentación'), ('ocupacion', 'Ocupación'), ('reportes', 'Reportes'), ('logs', 'Logs'), ('configuracion', 'Configuración')], max_length=50)),
                ('permission', models.CharField(choices=[('view', 'Ver'), ('create', 'Crear'), ('edit', 'Editar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('admin', 'Administrar')], max_length=20)),
                ('is_granted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso de Módulo',
                'verbose_name_plural': 'Permisos de Módulo',
                'ordering': ['module', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('superusuario', 'Superusuario'), ('administrador', 'Administrador'), ('catador', 'Catador'), ('pesador', 'Pesador'), ('operador', 'Operador'), ('supervisor', 'Supervisor'), ('invitado', 'Invitado')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_permissions', models.ManyToManyField(blank=True, related_name='custom_users', to='core.modulepermission')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.AddField(
            model_name='modulepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.userrole'),
        ),
        migrations.AlterUniqueTogether(
            name='modulepermission',
            unique_together={('module', 'permission', 'role')},
        ),
    ]
