# Generated by Django 4.2.7 on 2025-10-22 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modulepermission_userrole_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('backup_type', models.CharField(choices=[('database', 'Base de Datos'), ('media', 'Archivos Media'), ('full', 'Backup Completo')], max_length=20, verbose_name='Tipo de Backup')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=20, verbose_name='Frecuencia')),
                ('hour', models.IntegerField(default=2, verbose_name='Hora (0-23)')),
                ('minute', models.IntegerField(default=0, verbose_name='Minuto (0-59)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('upload_to_s3', models.BooleanField(default=False, verbose_name='Subir a S3')),
                ('retention_days', models.IntegerField(default=30, verbose_name='Días de Retención')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Ejecución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Programación de Backup',
                'verbose_name_plural': 'Programaciones de Backup',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('database', 'Base de Datos'), ('media', 'Archivos Media'), ('full', 'Backup Completo')], max_length=20, verbose_name='Tipo de Backup')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En Progreso'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Ruta del Archivo')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('s3_url', models.CharField(blank=True, max_length=500, verbose_name='URL S3')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duración')),
                ('task_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Tarea')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
            ],
            options={
                'verbose_name': 'Registro de Backup',
                'verbose_name_plural': 'Registros de Backup',
                'ordering': ['-started_at'],
            },
        ),
    ]
