# Generated by Django 4.2.7 on 2025-09-17 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('area_type', models.CharField(choices=[('guardeola', 'Guardeola'), ('pila', 'Pila'), ('horno', 'Horno'), ('humedo', 'Húmedo'), ('otra', 'Otra')], max_length=20, verbose_name='Tipo')),
                ('capacity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['name'],
            },
        ),
    ]
