# Generated by Django 4.2.7 on 2025-11-04 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CherryReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_code', models.CharField(help_text='Código único de identificación', max_length=50, unique=True, verbose_name='Código de Recepción')),
                ('weight_qq', models.DecimalField(decimal_places=2, help_text='Peso en quintales extraído de la foto', max_digits=10, verbose_name='Peso (qq)')),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en libras (calculado automáticamente)', max_digits=10, null=True, verbose_name='Peso (lbs)')),
                ('quality', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bueno'), ('regular', 'Regular'), ('poor', 'Deficiente')], default='good', max_length=20, verbose_name='Calidad')),
                ('humidity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad (%)')),
                ('scale_image', models.ImageField(upload_to='cherry_receptions/scales/%Y/%m/%d/', verbose_name='Foto del Reloj/Báscula')),
                ('ocr_raw_text', models.TextField(blank=True, help_text='Texto completo extraído de la imagen', verbose_name='Texto OCR sin procesar')),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Confianza OCR (%)')),
                ('ocr_processed', models.BooleanField(default=False, verbose_name='OCR Procesado')),
                ('manual_correction', models.BooleanField(default=False, help_text='Si el peso fue corregido manualmente', verbose_name='Corrección Manual')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En Proceso'), ('completed', 'Completado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('reception_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cherry_receptions', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cherry_receptions', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Recepción de Cereza',
                'verbose_name_plural': 'Recepciones de Cereza',
                'ordering': ['-reception_date'],
            },
        ),
        migrations.CreateModel(
            name='CherryReceptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cherry_receptions/additional/%Y/%m/%d/', verbose_name='Imagen')),
                ('image_type', models.CharField(choices=[('scale', 'Báscula/Reloj'), ('sample', 'Muestra de Cereza'), ('truck', 'Camión/Vehículo'), ('quality', 'Control de Calidad'), ('other', 'Otra')], default='other', max_length=20, verbose_name='Tipo de Imagen')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='cherry_reception.cherryreception', verbose_name='Recepción')),
            ],
            options={
                'verbose_name': 'Imagen de Recepción',
                'verbose_name_plural': 'Imágenes de Recepción',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cherryreception',
            index=models.Index(fields=['-reception_date'], name='cherry_rece_recepti_419316_idx'),
        ),
        migrations.AddIndex(
            model_name='cherryreception',
            index=models.Index(fields=['supplier', '-reception_date'], name='cherry_rece_supplie_6d6b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cherryreception',
            index=models.Index(fields=['status'], name='cherry_rece_status_e3d9bd_idx'),
        ),
    ]
