# Generated by Django 4.2.7 on 2025-11-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cherry_reception', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cherryreception',
            name='humidity_percentage',
        ),
    ]
