# Generated by Django 4.2.7 on 2025-09-17 02:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('finca', models.CharField(max_length=100, verbose_name='Finca')),
                ('variety', models.CharField(max_length=100, verbose_name='Variedad')),
                ('sublot', models.CharField(blank=True, max_length=50, verbose_name='Sublote')),
                ('initial_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Inicial (kg)')),
                ('initial_humidity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], verbose_name='Humedad Inicial (%)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('responsible', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='areas.area', verbose_name='Área Actual')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
