# Generated by Django 4.2.7 on 2025-09-17 02:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catador',
                'verbose_name_plural': 'Catadores',
            },
        ),
        migrations.CreateModel(
            name='Cupping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('method', models.CharField(choices=[('sca', 'SCA'), ('coe', 'COE'), ('custom', 'Personalizado')], default='sca', max_length=20, verbose_name='Método')),
                ('roast_level', models.CharField(blank=True, max_length=100, verbose_name='Nivel de Tueste')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_calibration', models.BooleanField(default=False, verbose_name='Es Calibración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuppings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catación',
                'verbose_name_plural': 'Cataciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CuppingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_code', models.CharField(max_length=50, verbose_name='Código Ciego')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cupping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='cupping.cupping')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupping_samples', to='lots.lot')),
            ],
            options={
                'verbose_name': 'Muestra de Catación',
                'verbose_name_plural': 'Muestras de Catación',
            },
        ),
        migrations.CreateModel(
            name='CuppingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragrance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('aroma', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('flavor', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('aftertaste', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('acidity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('body', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('uniformity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('clean_cup', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('sweetness', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('balance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('overall', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('defects', models.CharField(blank=True, max_length=500, verbose_name='Defectos')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cupper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='cupping.cupper')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='cupping.cuppingsample')),
            ],
            options={
                'verbose_name': 'Puntaje de Catación',
                'verbose_name_plural': 'Puntajes de Catación',
            },
        ),
    ]
