# Generated by Django 4.2.7 on 2025-09-20 03:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cupping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupping',
            options={'ordering': ['-date'], 'verbose_name': 'Sesión de Catación', 'verbose_name_plural': 'Sesiones de Catación'},
        ),
        migrations.AlterModelOptions(
            name='cuppingsample',
            options={'ordering': ['order', 'blind_code'], 'verbose_name': 'Muestra de Catación', 'verbose_name_plural': 'Muestras de Catación'},
        ),
        migrations.RemoveField(
            model_name='cupping',
            name='method',
        ),
        migrations.RemoveField(
            model_name='cupping',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cupping',
            name='roast_level',
        ),
        migrations.RemoveField(
            model_name='cupping',
            name='title',
        ),
        migrations.AddField(
            model_name='cupper',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('qc_leader', 'Líder de Calidad'), ('cupper', 'Catador'), ('guest', 'Invitado')], default='cupper', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='cupping',
            name='blinding',
            field=models.CharField(choices=[('none', 'No ciego'), ('blind', 'Ciego'), ('double', 'Doble ciego')], default='blind', max_length=20, verbose_name='Tipo de Cegado'),
        ),
        migrations.AddField(
            model_name='cupping',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cerrada en'),
        ),
        migrations.AddField(
            model_name='cupping',
            name='is_realtime',
            field=models.BooleanField(default=True, verbose_name='Tiempo Real'),
        ),
        migrations.AddField(
            model_name='cupping',
            name='label_type',
            field=models.CharField(choices=[('alpha', 'Alfabético (A/B/C)'), ('numeric', 'Numérico (1/2/3)'), ('trilet', '3 Letras (ABC/DEF)')], default='alpha', max_length=20, verbose_name='Tipo de Etiqueta'),
        ),
        migrations.AddField(
            model_name='cupping',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='cupping',
            name='name',
            field=models.CharField(default='Nueva Sesión', max_length=200, verbose_name='Nombre de la Sesión'),
        ),
        migrations.AddField(
            model_name='cupping',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Abierta en'),
        ),
        migrations.AddField(
            model_name='cupping',
            name='protocol',
            field=models.CharField(choices=[('sca', 'SCA Clásico'), ('cva', 'CVA 2024'), ('coe', 'Cup of Excellence'), ('custom', 'Personalizado')], default='sca', max_length=20, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='cupping',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('open', 'Abierta'), ('closed', 'Cerrada')], default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='grind',
            field=models.CharField(blank=True, max_length=50, verbose_name='Molido'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='harvest',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cosecha'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='origin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='process',
            field=models.CharField(blank=True, max_length=100, verbose_name='Proceso'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='ratio',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ratio'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='roast_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Tueste'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='roast_profile',
            field=models.CharField(blank=True, max_length=100, verbose_name='Perfil de Tueste'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='temperature',
            field=models.CharField(blank=True, max_length=20, verbose_name='Temperatura'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='variety',
            field=models.CharField(blank=True, max_length=100, verbose_name='Variedad'),
        ),
        migrations.AddField(
            model_name='cuppingsample',
            name='water',
            field=models.CharField(blank=True, max_length=100, verbose_name='Agua'),
        ),
        migrations.AddField(
            model_name='cuppingscore',
            name='affective_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='Puntajes Afectivos'),
        ),
        migrations.AddField(
            model_name='cuppingscore',
            name='descriptive_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='Puntajes Descriptivos'),
        ),
        migrations.AddField(
            model_name='cuppingscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cupper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupper_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cupping',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cuppings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cupping',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha de Catación'),
        ),
        migrations.AlterField(
            model_name='cuppingsample',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupping_samples', to='lots.lot'),
        ),
        migrations.AlterUniqueTogether(
            name='cupper',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='cuppingscore',
            unique_together={('sample', 'cupper')},
        ),
        migrations.CreateModel(
            name='CuppingSessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cupper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cupping.cupper')),
                ('cupping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cupping.cupping')),
            ],
            options={
                'verbose_name': 'Participante de Sesión',
                'verbose_name_plural': 'Participantes de Sesión',
                'unique_together': {('cupping', 'cupper')},
            },
        ),
        migrations.CreateModel(
            name='CuppingDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=100, verbose_name='Descriptor')),
                ('intensity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Intensidad')),
                ('polarity', models.CharField(choices=[('positive', 'Positivo'), ('negative', 'Negativo')], default='positive', max_length=10, verbose_name='Polaridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cupper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='cupping.cupper')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='cupping.cuppingsample')),
            ],
            options={
                'verbose_name': 'Descriptor de Sabor',
                'verbose_name_plural': 'Descriptores de Sabor',
                'unique_together': {('sample', 'cupper', 'descriptor')},
            },
        ),
    ]
