# Generated by Django 4.2.7 on 2025-10-20 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupping', '0002_alter_cupping_options_alter_cuppingsample_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialCupping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ingreso', models.CharField(max_length=100, unique=True, verbose_name='Número de Ingreso')),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Humedad (%)')),
                ('rendimiento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rendimiento (%)')),
                ('apariencia_verde', models.CharField(choices=[('Excelente', 'Excelente'), ('Muy Buena', 'Muy Buena'), ('Buena', 'Buena'), ('Regular', 'Regular'), ('Mala', 'Mala')], max_length=20, verbose_name='Apariencia Verde')),
                ('tueste', models.CharField(choices=[('Claro', 'Claro'), ('Medio', 'Medio'), ('Oscuro', 'Oscuro'), ('Muy Oscuro', 'Muy Oscuro')], max_length=20, verbose_name='Tueste')),
                ('quakers', models.PositiveIntegerField(default=0, verbose_name='Quakers')),
                ('tipo', models.CharField(choices=[('Prima Lavado', 'Prima Lavado'), ('Extra Prima', 'Extra Prima'), ('Semi Lavado', 'Semi Lavado'), ('Natural', 'Natural'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo')),
                ('taza', models.CharField(max_length=200, verbose_name='Taza')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_catacion', models.DateField(verbose_name='Fecha de Catación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catación Comercial',
                'verbose_name_plural': 'Cataciones Comerciales',
                'ordering': ['-fecha_catacion'],
            },
        ),
    ]
