# Generated by Django 4.2.7 on 2025-10-20 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cupping', '0003_commercialcupping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cupper',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cupper',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('qc_leader', 'Líder de Calidad'), ('taster', 'Catador'), ('guest', 'Invitado')], default='taster', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='cupper',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupper_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
