# Generated by Django 4.2.7 on 2025-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupping', '0004_alter_cupper_unique_together_alter_cupper_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialcupping',
            name='quakers',
            field=models.CharField(choices=[('No', 'No'), ('Pocos', 'Pocos'), ('Varios', 'Varios'), ('Bastantes', 'Bastantes')], default='No', max_length=20, verbose_name='Quakers'),
        ),
    ]
