# Generated by Django 4.2.7 on 2025-10-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupping', '0005_alter_commercialcupping_quakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialcupping',
            name='tipo',
            field=models.CharField(choices=[('Estrictamente Duro (SHB)', 'Estrictamente Duro (SHB)'), ('Duro (HB)', 'Duro (HB)'), ('Semi Duro', 'Semi Duro'), ('Extra Prime', 'Extra Prime'), ('Prime', 'Prime'), ('Supremo', 'Supremo'), ('Excelso', 'Excelso'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo'),
        ),
    ]
