# Generated by Django 4.2.7 on 2025-10-24 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupping', '0006_alter_commercialcupping_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialcupping',
            name='qq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='QQ (Peso en quintales)'),
        ),
    ]
