# Generated by Django 4.2.7 on 2025-10-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('type', models.CharField(choices=[('cc1', 'Café Cereza CC1'), ('parchment', 'Café Pergamino'), ('both', 'Ambos Tipos')], max_length=20, verbose_name='Tipo de Café')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Persona de Contacto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20, verbose_name='Estado')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Calificación')),
                ('total_deliveries', models.IntegerField(default=0, verbose_name='Total de Entregas')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso Total (qq)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
    ]
