# Generated by Django 4.2.7 on 2025-10-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_supervisor_remove_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='shift_type',
            field=models.CharField(choices=[('turno_a', 'Turno A (Lunes 8AM - Martes 8AM)'), ('turno_b', 'Turno B (Martes 8AM - Miércoles 8AM)')], max_length=10, verbose_name='Turno'),
        ),
    ]
