# Generated by Django 4.2.7 on 2025-10-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_supervisor_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dpi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DPI'),
        ),
    ]
