# Generated by Django 4.2.7 on 2025-11-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_dpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='email',
        ),
    ]
