# Generated by Django 4.2.7 on 2025-09-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperatura'), ('humidity', 'Humedad'), ('ph', 'pH'), ('pressure', 'Presión'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_reading_time', models.DateTimeField(blank=True, null=True, verbose_name='Última Lectura')),
                ('last_reading_value', models.FloatField(blank=True, null=True, verbose_name='Último Valor')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='areas.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['code'],
            },
        ),
    ]
