# Generated by Django 4.2.7 on 2025-11-05 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Raspberry Pi',
                'verbose_name_plural': 'Raspberry Pis',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperatura'), ('humidity', 'Humedad'), ('ph', 'pH'), ('pressure', 'Presión'), ('distance', 'Distancia'), ('other', 'Otro')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='SensorTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pin_cs', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('raspberry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores_temperatura', to='sensors.raspberrypi')),
            ],
            options={
                'verbose_name': 'Sensor de Temperatura',
                'verbose_name_plural': 'Sensores de Temperatura',
                'ordering': ['raspberry', 'nombre'],
                'unique_together': {('raspberry', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Recipiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('fermentacion', 'Pila de Fermentación'), ('secado', 'Pila de Secado')], default='fermentacion', max_length=20)),
                ('pin_trig', models.IntegerField(blank=True, null=True)),
                ('pin_echo', models.IntegerField(blank=True, null=True)),
                ('distancia_sensor', models.FloatField(default=30.0)),
                ('profundidad', models.FloatField(default=220.0)),
                ('distancia_vacia', models.FloatField(default=268.0)),
                ('distancia_llena', models.FloatField(default=118.0)),
                ('pin_cs', models.IntegerField(blank=True, null=True)),
                ('spi_bus', models.IntegerField(blank=True, default=0, null=True)),
                ('spi_device', models.IntegerField(blank=True, default=0, null=True)),
                ('temp_min', models.FloatField(default=-10.0)),
                ('temp_max', models.FloatField(default=80.0)),
                ('temp_warning', models.FloatField(default=50.0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('raspberry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipientes', to='sensors.raspberrypi')),
            ],
            options={
                'verbose_name': 'Recipiente',
                'verbose_name_plural': 'Recipientes',
                'ordering': ['raspberry', 'nombre'],
                'unique_together': {('raspberry', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MedicionTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('estado', models.CharField(choices=[('OK', 'Normal'), ('WARNING', 'Alerta'), ('ERROR', 'Error')], default='OK', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raspberry_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='sensors.sensortemperatura')),
            ],
            options={
                'verbose_name': 'Medición de Temperatura',
                'verbose_name_plural': 'Mediciones de Temperatura',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='sensors_med_sensor__d9fb99_idx'), models.Index(fields=['-timestamp'], name='sensors_med_timesta_4beda9_idx'), models.Index(fields=['estado', '-timestamp'], name='sensors_med_estado_84eb7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_cm', models.FloatField()),
                ('porcentaje_llenado', models.FloatField()),
                ('estado', models.CharField(blank=True, choices=[('Vacío', 'Vacío (0-10%)'), ('Llenando', 'Llenando (11-75%)'), ('Lleno', 'Lleno (76-100%)')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raspberry_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('recipiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='sensors.recipiente')),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['recipiente', '-timestamp'], name='sensors_med_recipie_981ee9_idx'), models.Index(fields=['-timestamp'], name='sensors_med_timesta_a15770_idx'), models.Index(fields=['estado', '-timestamp'], name='sensors_med_estado_f56cc3_idx')],
            },
        ),
    ]
