# Generated by Django 4.2.7 on 2025-09-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fermentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('target_hours', models.FloatField(verbose_name='Objetivo (horas)')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('status', models.CharField(choices=[('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='in_progress', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermentations', to='lots.lot')),
            ],
            options={
                'verbose_name': 'Fermentación',
                'verbose_name_plural': 'Fermentaciones',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FermentationMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ph', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fermentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='fermentation.fermentation')),
            ],
            options={
                'verbose_name': 'Medición de Fermentación',
                'verbose_name_plural': 'Mediciones de Fermentación',
                'ordering': ['-timestamp'],
            },
        ),
    ]
