# Generated by Django 4.2.7 on 2025-09-24 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('report_type', models.CharField(choices=[('daily_production', 'Producción Diaria'), ('temperature_summary', 'Resumen de Temperaturas'), ('attendance_summary', 'Resumen de Asistencia'), ('occupation_summary', 'Resumen de Ocupación'), ('lot_progress', 'Progreso de Lotes'), ('fermentation_report', 'Reporte de Fermentación'), ('cupping_report', 'Reporte de Catación'), ('employee_performance', 'Rendimiento de Empleados'), ('quality_control', 'Control de Calidad'), ('custom', 'Personalizado')], max_length=50, verbose_name='Tipo de Reporte')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='Formato')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('generating', 'Generando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='draft', max_length=20, verbose_name='Estado')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parámetros')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Ruta del Archivo')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Descargas')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('report_type', models.CharField(max_length=50, verbose_name='Tipo de Reporte')),
                ('template_type', models.CharField(choices=[('html', 'HTML'), ('latex', 'LaTeX'), ('jinja2', 'Jinja2'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo de Plantilla')),
                ('template_content', models.TextField(verbose_name='Contenido de la Plantilla')),
                ('css_content', models.TextField(blank=True, verbose_name='Estilos CSS')),
                ('is_default', models.BooleanField(default=False, verbose_name='Plantilla por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Programación')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('custom', 'Personalizado')], max_length=20, verbose_name='Frecuencia')),
                ('cron_expression', models.CharField(blank=True, max_length=100, verbose_name='Expresión Cron')),
                ('email_recipients', models.JSONField(default=list, verbose_name='Destinatarios Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Ejecución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.report')),
            ],
            options={
                'verbose_name': 'Programación de Reporte',
                'verbose_name_plural': 'Programaciones de Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('debug', 'Debug')], max_length=20, verbose_name='Nivel')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('details', models.JSONField(default=dict, verbose_name='Detalles')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reports.report')),
            ],
            options={
                'verbose_name': 'Log de Reporte',
                'verbose_name_plural': 'Logs de Reportes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Datos en Cache')),
                ('cache_key', models.CharField(max_length=200, unique=True, verbose_name='Clave de Cache')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_data', to='reports.report')),
            ],
            options={
                'verbose_name': 'Datos de Reporte en Cache',
                'verbose_name_plural': 'Datos de Reportes en Cache',
            },
        ),
    ]
