# Generated by Django 4.2.7 on 2025-10-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('attendance', 'Asistencias'), ('cupping', 'Cataciones'), ('shipping_weights', 'Pesos de Envío'), ('integrations', 'Integraciones'), ('temperature', 'Temperaturas'), ('occupation', 'Ocupación'), ('daily_production', 'Producción Diaria'), ('attendance_summary', 'Resumen de Asistencia'), ('temperature_summary', 'Resumen de Temperaturas'), ('occupation_summary', 'Resumen de Ocupación'), ('lot_progress', 'Progreso de Lotes'), ('fermentation_report', 'Reporte de Fermentación'), ('cupping_report', 'Reporte de Catación'), ('employee_performance', 'Rendimiento de Empleados'), ('quality_control', 'Control de Calidad'), ('custom', 'Personalizado')], max_length=50, verbose_name='Tipo de Reporte'),
        ),
    ]
