# Generated by Django 4.2.7 on 2025-09-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('unit', models.CharField(default='°C', max_length=10, verbose_name='Unidad')),
                ('quality', models.CharField(choices=[('good', 'Buena'), ('warning', 'Advertencia'), ('error', 'Error')], default='good', max_length=20, verbose_name='Calidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', 'timestamp'], name='temperature_sensor__032ad4_idx'), models.Index(fields=['timestamp'], name='temperature_timesta_a8affc_idx')],
            },
        ),
    ]
